from . import sale_order
from . import product_template
from . import purchase_order_line
from . import sale_order_approval
from . import sale_order_checklist
from . import res_partner
from . import account_move
from . import stock_picking
from . import project_extension
from . import product_url